add a blog post about rusty's usage on atoum
atoum/atoum.github.io pull request #54
Opened 2016-10-05 19:49 UTC by agallou

2016-10-05 19:50 UTC, agallou commented
@blueclock you've recently improved the english version of the documentation: will you be willing to have a look on this post ?

2016-10-05 20:06 UTC, blueclock commented
@agallou avec plaisir :-)

2016-10-05 20:37 UTC, jubianchi requested changes

2016-10-05 20:37 UTC, jubianchi commented on _posts/2016-12-31-improving-atoum-documentation-with-rust.markdown
> +atoum's documentation contains a lot of PHP examples. Sometimes, some of them did not work : those examples contained syntax errors.
`s/those examples/they/`

2016-10-05 20:37 UTC, jubianchi commented on _posts/2016-12-31-improving-atoum-documentation-with-rust.markdown
> +atoum's documentation contains a lot of PHP examples. Sometimes, some of them did not work : those examples contained syntax errors.
I would have merged this sentence with the next one:

> [...] some of them did not work : they contained syntax errors like the one below. A semicolon [...]

2016-10-05 20:37 UTC, jubianchi commented on _posts/2016-12-31-improving-atoum-documentation-with-rust.markdown
> +Like this one below : a semicolon were missing at the end of the line. So, a user pasting it did not had a working example.
`s/were missing/was missing/`

2016-10-05 20:37 UTC, jubianchi commented on _posts/2016-12-31-improving-atoum-documentation-with-rust.markdown
> +[Rusty](https://github.com/K-Phoen/Rusty) is a tool written in PHP by [Kevin Gomez](http://www.kevingomez.fr/), that extracts code blocs within phpdoc blocks or markdown, and execute or lint them (th
`s/, that/. It/`

2016-10-05 20:37 UTC, jubianchi commented on _posts/2016-12-31-improving-atoum-documentation-with-rust.markdown
> +[Rusty](https://github.com/K-Phoen/Rusty) is a tool written in PHP by [Kevin Gomez](http://www.kevingomez.fr/), that extracts code blocs within phpdoc blocks or markdown, and execute or lint them (th
`s/the author as written/the author wrote/`

2016-10-05 20:37 UTC, jubianchi commented on _posts/2016-12-31-improving-atoum-documentation-with-rust.markdown
> +Rusty supported markdown, but not RST. Fortunately, the architecture were in place on Rusty to add new formats. So we've made a [pull Request](https://github.com/K-Phoen/Rusty/pull/1) to add support
> the architecture in place in Rusty allows to add new formats.

2016-10-05 20:37 UTC, jubianchi commented on _posts/2016-12-31-improving-atoum-documentation-with-rust.markdown
> +Rusty supported markdown, but not RST. Fortunately, the architecture were in place on Rusty to add new formats. So we've made a [pull Request](https://github.com/K-Phoen/Rusty/pull/1) to add support
double space between "RST" and "("

2016-10-05 20:37 UTC, jubianchi commented on _posts/2016-12-31-improving-atoum-documentation-with-rust.markdown
> +Rusty could be launch like this:
> We can start Rusty with this command:

2016-10-05 20:37 UTC, jubianchi commented on _posts/2016-12-31-improving-atoum-documentation-with-rust.markdown
> +This command launches rusty without executing the content of the founded blocs (it only lints their content) of the files from the "source" folder.
> Doing so will only lint the found code blocks in files inside the `source` folder.

2016-10-05 20:37 UTC, jubianchi commented on _posts/2016-12-31-improving-atoum-documentation-with-rust.markdown
> +The result of this command gives an output like this:
`s/gives an output like this/looks like this/`

2016-10-05 20:37 UTC, jubianchi commented on _posts/2016-12-31-improving-atoum-documentation-with-rust.markdown
> +* will seek for supported file extensions (php, markdown, and RST);
`s/seek/look/`

2016-10-05 20:37 UTC, jubianchi commented on _posts/2016-12-31-improving-atoum-documentation-with-rust.markdown
> +* if php code are found, it will lint it : check that the syntax is correct
`s/are found/is found/`

2016-10-05 20:37 UTC, jubianchi commented on _posts/2016-12-31-improving-atoum-documentation-with-rust.markdown
> +* in case of the syntax is not correct, the php code will be displayed alongside the error message.
`s/in case of the syntax is not correct/if the syntax is not correct/`

2016-10-05 20:37 UTC, jubianchi commented on _posts/2016-12-31-improving-atoum-documentation-with-rust.markdown
> +Fixing mistakes is a good this : avoid to having them appear ever again is better.
no space before ":" in english ;)

2016-10-05 20:37 UTC, jubianchi commented on _posts/2016-12-31-improving-atoum-documentation-with-rust.markdown
> +Fixing mistakes is a good this : avoid to having them appear ever again is better.
`s/avoid to having them appear/avoiding them to appear/`

2016-10-05 20:37 UTC, jubianchi commented on _posts/2016-12-31-improving-atoum-documentation-with-rust.markdown
> +For that we've added a travis configuration to our documentation repository in order to alert (via the [pull request status](https://github.com/blog/1935-see-results-from-all-pull-request-status-chec
`s/For that/To prevent such errors/`

2016-10-06 20:38 UTC, Grummfy approved these changes

2016-10-06 20:38 UTC, Grummfy commented on _posts/2016-12-31-improving-atoum-documentation-with-rust.markdown
> +atoum's documentation contains a lot of PHP examples. Sometimes they don't work because of syntax errors.
link to documentation?

2016-10-06 20:38 UTC, Grummfy commented on _posts/2016-12-31-improving-atoum-documentation-with-rust.markdown
> +   $string = 'atoum'
give the output of rusty in this case (screenshot or text)?

2016-10-07 09:29 UTC, jubianchi commented on _posts/2016-12-31-improving-atoum-documentation-with-rust.markdown
> +The result of this command is the following output:
"The previous command yields the following output:"

2016-10-07 09:37 UTC, jubianchi approved these changes

2016-10-07 09:38 UTC, jubianchi requested changes

2016-10-07 09:38 UTC, jubianchi commented on _posts/2016-12-31-improving-atoum-documentation-with-rust.markdown
> +The result of this command is the following output:
"The previous command yields the following output:"

2016-11-21 16:36 UTC, jubianchi approved these changes

2016-11-21 16:36 UTC, merged