Post about GLPI using atoum
atoum/atoum.github.io pull request #67
Opened 2017-08-03 19:30 UTC by Grummfy

I finally got time to do it!

2017-08-03 20:23 UTC, mikaelrandy reviewed
Seems a little bit too close to Google translation ;)

2017-08-03 20:23 UTC, mikaelrandy commented on _posts/2017-08-10-glpi-atoum.markdown
> +The [GLPI project][GLPI] [recently announced][announced-en][^1] that they have migrated to atoum for their unit test suite. So let's get back on
they have migrated their unit test suite to atoum.

2017-08-03 20:23 UTC, mikaelrandy commented on _posts/2017-08-10-glpi-atoum.markdown
> +this news. We ask several questions to the official team of the project to have some feedback, [Johan Cwiklinski](https://github.com/trasher)
We interviewed Johan Cwiklinski and some other members of the project official team about this migration.

2017-08-03 20:23 UTC, mikaelrandy commented on _posts/2017-08-10-glpi-atoum.markdown
> +Since 2015; we are trying to rewrite and modernise the whole project, starting with the backend.
modernize

2017-08-03 20:23 UTC, mikaelrandy commented on _posts/2017-08-10-glpi-atoum.markdown
> +At first, one regular contributor has tried to add unit tests into the project in 2010. But project managers did not follow him, and this has quickly been abandoned.
Firstly
this was quickly abandoned.

2017-08-03 20:23 UTC, mikaelrandy commented on _posts/2017-08-10-glpi-atoum.markdown
> +Then, in 2015, the same contributor has tried again to add tests on the project; with much more success :)
The same contributor tried again

2017-08-03 20:23 UTC, mikaelrandy commented on _posts/2017-08-10-glpi-atoum.markdown
> +## 3. What were the issues you were facing with PHPUnit? Why did you choose atoum instead of other tools to resolve it?
What kind of difficulties do you encounter

2017-08-03 20:23 UTC, mikaelrandy commented on _posts/2017-08-10-glpi-atoum.markdown
> +Well... We had to entirely rewrite our tests. It’s more a painful than a difficult work at first; but finally, we’ve not spent that much time on the rewrite process.
we havent spent too much time on this rewrite work.

2017-08-03 20:23 UTC, mikaelrandy commented on _posts/2017-08-10-glpi-atoum.markdown
> +Another issue was that atoum is much less permissive than PHPUnit per default; but this was not an issue because we got many little things fixed (such a PHP notices...).
this was not a real issue

2017-08-03 20:23 UTC, mikaelrandy commented on _posts/2017-08-10-glpi-atoum.markdown
> +Teclib has been involved in a project to adapt it to match SoC (Security operation centre) requirements. The project had also been an opportunity to develop a REST API.
A link on Teclib word ?

2017-08-04 07:21 UTC, Grummfy commented
thanks for your review  @mikaelrandy

2017-08-05 07:45 UTC, mikaelrandy approved these changes

2017-08-07 08:42 UTC, Hywan requested changes
Thanks for taking time for that!

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +The [GLPI project][GLPI] [recently announced][announced-en][^1] that they have migrated their unit test suite to atoum. So let's get back on
```diff
- suite
+ suites
```

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +Since 2015; we are trying to rewrite and modernize the whole project, starting with the backend.
```diff
- 2015;
+ 2015,
```

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +Firstly, one regular contributor has tried to add unit tests into the project in 2010. But project managers did not follow him, and this was quickly abandoned.
```diff
- this
+ it
```

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +Then, in 2015, The same contributor tried again to add tests on the project; with much more success :)
```diff
- Then, in 2015, The same
+ Forward to 2015, the same
```

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +We didn’t really face issues with PHPUnit. This is more a choice that was dictated by atoum capabilities; like:
```diff
- choice
+ technical choice
```

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +We didn’t really face issues with PHPUnit. This is more a choice that was dictated by atoum capabilities; like:
```diff
- dictated
+ led
```

(still not convinced by “led”, but much better than “dictated”).

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +* wonderful mocking system (that allows mocking PHP native functions, constants, ...),
```diff
- , ...
+ …
```

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +* use closure to test outputs, exceptions, ... (way more interesting than phpunit’s annotations),
```diff
- , ...
+ …
```

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +* use closure to test outputs, exceptions, ... (way more interesting than phpunit’s annotations),
```diff
- phpunit's
+ PHPUnit's
```

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +* concurrent run of tests (even if it has been disabled for GLPI),
```diff
- tests
+ test cases
```

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +* fully isolated tests,
```diff
- tests
+ test cases
```

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +Last but not least; atoum is a French project at the origin; just like GLPI!
```diff
- least;
+ least:
```

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +## 4. Did you meet some issue during the migration from PHPUnit to atoum?
```diff
- meet
+ face
```

```diff
- some issue
+ some issues
```

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +Well... We had to entirely rewrite our tests. It’s more a painful than a difficult work at first; but finally, we haven't spent too much time on this rewrite work.
```diff
- Well...
+ Well…
```

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +Well... We had to entirely rewrite our tests. It’s more a painful than a difficult work at first; but finally, we haven't spent too much time on this rewrite work.
```diff
- our tests
+ our test suites
```

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +Well... We had to entirely rewrite our tests. It’s more a painful than a difficult work at first; but finally, we haven't spent too much time on this rewrite work.
```diff
- a painful
+ painful
```

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +Well... We had to entirely rewrite our tests. It’s more a painful than a difficult work at first; but finally, we haven't spent too much time on this rewrite work.
Do we have some numbers here? Time *t* spent to rewrite *x* test suites of *y* test cases? Did they find new bugs? What about the execution time? Is it easier now to write new tests? Is it easier for newcomers to write or to maintain new test suites?

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +We did have a really basic usage of PHPUnit; the only thing that required much more work was the `@depends`[^2] capability of PHPUnit.
```diff
- ; the only
+ . The only
```

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +That was quite easy to change; and has benefited: we now run all our tests from a fresh, out of the box GLPI environment.
```diff
- ; and has benefited: we
+ and brought some nice benefits: We
```

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +Another issue was that atoum is much less permissive than PHPUnit per default; but this was not a real issue because we got many little things fixed (such a PHP notices...).
```diff
- ; but this
+ , but this
```

```diff
- such a PHP notices...
+ such as PHP notices…
```

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +## 6. You recently receive a price related to security, can you tel us more about it?
```diff
- tel
+ tell
```

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +Being part of the OW2 Consortium community, GLPI received the 2017 Technology Council special prize for its work on addressing security requirements but also
Add link to OW2 Consortium please.

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +Being part of the OW2 Consortium community, GLPI received the 2017 Technology Council special prize for its work on addressing security requirements but also
Add link to the news or the tweet, with at least the photo!

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +the big working currently being made to modernise the framework. The jury has mentioned the implementation of unit tests and the switch from PHPUnit to atoum !
```diff
- atoum !
+ atoum!
```

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +## 7. Anything to add?
```diff
- Anything to add?
+ If you have anything else to say, please feel free!
```

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +When I’ve discovered atoum (I don’t remember exactly when, but that was far before the first semver release); I’ve immediately loved it. That was much
```diff
- ;
+ ,
```

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +clearer to me to understand and write tests; I began to like that! ;) I’ve used atoum in several closed source projects (even when the "frameworks" say
```diff
- ;
+ .
```

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +to use something else); but also in [Galette](http://galette.eu)[^3]; which has unit tests powered by atoum since 2013.
```diff
- ;
+ .
```

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +I would like to thank Johan and his team for this feedback, it was really interesting and I hope you also like it. If you use atoum on your project,
```diff
- this feedback
+ this valuable feedback
```

“it was really interesting” Why?

2017-08-07 08:42 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +we would be happy to hear some feedback about it, it's always interesting.
```diff
- feedback
+ feedbacks
```

```diff
- interesting
+ important
```

2017-08-07 13:35 UTC, Grummfy commented
thanks @Hywan for the review. 
For information I don't know which is good but antidote is saying that modernize is American and modernise is British... For me it's the same, but I let modernise, if you think it's important I will change it. Same for feedback it say that it's not countable ... 
So except for theses two points I have made the change reviewed.

2017-08-07 13:48 UTC, Hywan commented
Modernise is English 🇬🇧, modernize is simplified English 🇺🇸.
Use English.

Yes, “feedbacks” is incorrect, I forgot, sorry.

Thanks for the modifications! Why so many “;” before?

2017-08-07 13:57 UTC, Grummfy commented
Because the answer to the question was, what it was given to me by email, and there is a lot of ';'
So I just copy-paste the answer to my questions ;)

2017-08-07 14:34 UTC, trasher commented on _posts/2017-08-10-glpi-atoum.markdown
> +We didn’t really face issues with PHPUnit. This is more a choice that was dictated by atoum capabilities; like:
What about "This is more a technical choice for atoum capabilities"?

2017-08-09 07:23 UTC, Grummfy commented
@trasher an y extra comments?

2017-08-09 08:42 UTC, trasher commented
I've just send you by mail extra info you requested; it's OK for me :)

2017-08-09 11:18 UTC, Grummfy commented
SO I think it's ready : @Hywan &  @mikaelrandy I would like to have a last feedback from you

2017-08-09 12:28 UTC, Hywan requested changes

2017-08-09 12:28 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +## 1. Can you summary the GLPI project and the usage of PHP inside it?
```diff
- summary
+ summarize
```

2017-08-09 12:28 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +## 1. Can you summary the GLPI project and the usage of PHP inside it?
```diff
- the usage of PHP inside it?
+ its usage of PHP?
```

2017-08-09 12:28 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +## 2. When did you start using unit test for the project?
```diff
- unit test
+ unit tests
```

2017-08-09 12:28 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +## 3. What kinds of difficulties do you encounter with PHPUnit? Why did you choose atoum instead of other tools to resolve it?
```diff
- kinds
+ kind
```

2017-08-09 12:28 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +## 3. What kinds of difficulties do you encounter with PHPUnit? Why did you choose atoum instead of other tools to resolve it?
```diff
- do you
+ did you
```

2017-08-09 12:28 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +In some case, due to the current GLPI code, some tests could not be run concurrently, this cause unpredictable results. Also, GLPI use a huge
```diff
- Also, GLPI use
+ Also, GLPI uses
```

2017-08-09 12:28 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +* There were about 2600 assertions with PHPUnit, but more than 5000 with atoum. This came for various reasons, one was that many returns were not tested and lend to un-understandable situations,
```diff
- lend
+ led
```

?

2017-08-09 12:28 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +* I’ve spent about *2 or 3 work days* to achieve the *complete migration*. I’ve also taken a few hours to migrate already opened pull requests that provided unit tests.
```diff
- provided unit tests.
+ provided unit tests,
```

2017-08-09 12:28 UTC, Hywan commented on _posts/2017-08-10-glpi-atoum.markdown
> +* Since atoum migration, some tests have been added. We now test 66 classes with 9000 assertions.[^3] :)
```diff
- assertions.[^3]
+ assertions,[^3]
```

2017-08-09 14:44 UTC, Grummfy commented
@Hywan thanks, fixed ;)

2017-08-10 08:27 UTC, merged