[WIP]Release policy
atoum/atoum.github.io pull request #68
Opened 2017-08-03 20:48 UTC by Grummfy

* adding page about release policy (new one)
* change configuration of jekyll to have a pages collection, this will make it clearer ;)
* add the permalink configuration for the posts, to be sure it's properly handled and will not change in the future

2017-08-07 08:29 UTC, Hywan requested changes

2017-08-07 08:29 UTC, Hywan commented on _pages/about/release_policy.md
> +As said during the Forum PHP 2015, we should give our users a clear view of how/when we release atoum.
Link? Is it even necessary to say that?

2017-08-07 08:29 UTC, Hywan commented on _pages/about/release_policy.md
> +Here are some notes I have on this:
“Here are the rules we agreed on and we follow”?

2017-08-07 08:29 UTC, Hywan commented on _pages/about/release_policy.md
> +- **strictly stick to semver** (x++ if BC breaks, y++ for any new feature, z++ for any bug-fix)
Link to semver?

2017-08-07 08:29 UTC, Hywan commented on _pages/about/release_policy.md
> +- release **ASAP for any bug** (patch)
Unfold the acronym: ASAP -> as soon as possible.

2017-08-07 08:29 UTC, Hywan commented on _pages/about/release_policy.md
> +@atoum/rms feel free to comment on this, suggest new entry or fix some of them. Once we are OK with those rules, I'll write a blog post.
You must say that —by default— atoum is rolling-released. But to fit in real world constraints, we have adopted semver. So by default, `master` is always stable and represent the latest version. This is important to notice at first.

2017-08-07 08:29 UTC, Hywan commented
Thanks for taking time for that!

2017-08-08 19:38 UTC, Grummfy commented on _pages/about/release_policy.md
> +As said during the Forum PHP 2015, we should give our users a clear view of how/when we release atoum.
for now I just copy what is inside https://github.com/atoum/atoum.github.io/issues/16 I have not  work on the for yet

2017-08-08 20:29 UTC, Grummfy commented
@Hywan, @mikaelrandy & @jubianchi I would like to have your though on the content of this new page.

2017-08-10 09:02 UTC, mikaelrandy reviewed
I agree on this, but i ask myself if we should add a RELEASE.md on atoum/atoum explaining this.

2017-08-10 09:02 UTC, mikaelrandy approved these changes

2017-08-14 06:45 UTC, jubianchi requested changes

2017-08-14 06:45 UTC, jubianchi commented on _pages/about/release_policy.md
> +We try to support a previous major version until *one* year after the *last minor/patch* release.
`s/We try/We will/`

2017-08-14 06:45 UTC, jubianchi commented on _pages/about/release_policy.md
> +* the oldest major version will have its own branch and the newest will live on the master branch
add a `;` at the end

2017-08-14 06:45 UTC, jubianchi commented on _pages/about/release_policy.md
> +* bug-fixes will be backported
add a `;` at the end

2017-08-14 06:45 UTC, jubianchi commented on _pages/about/release_policy.md
> +the *master* branch is considered as stable and can be directly used without any issue and represent the latest stable version.
I would have used bold for `the *master* branch is considered as stable`

2017-08-14 06:45 UTC, jubianchi commented on _pages/about/release_policy.md
> +The officially supported extension[^1] has a different release policy. It's more released when it's ready:
```diff
-supported extension
+supported extensions
```

```diff
- It's more released when it's ready
+ They are released when they are ready
```

2017-08-14 06:45 UTC, jubianchi commented on _pages/about/release_policy.md
> +* if there is BC break, will be released in-sync with atoum for new atoum major release
```diff
- if there is BC break, will be
+ if there is any BC break in atoum, they will be
```

2017-08-14 06:45 UTC, jubianchi commented on _pages/about/release_policy.md
> +* if there is BC break, will be released in-sync with atoum for new atoum major release
add a `;` at the end

2017-08-14 06:45 UTC, jubianchi commented on _pages/about/release_policy.md
> +* may be released at the same time (minor)
add a ; at the end

2017-08-14 07:36 UTC, mikaelrandy commented on _pages/about/release_policy.md
> +We try to support a previous major version until *one* year after the *last minor/patch* release.
`we will try` or `we will support` ?

2017-08-14 11:52 UTC, jubianchi commented on _pages/about/release_policy.md
> +We try to support a previous major version until *one* year after the *last minor/patch* release.
indeed:

```diff
- We try to support
+ We will support
```

2017-08-14 14:30 UTC, Grummfy commented
I have made the fix from @jubianchi . I also edit the source page to remove release process from it and merge it into the release policy page. I also add a contact page.

For me, now it's finished.

2017-10-02 15:49 UTC, merged